spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/train_db_dev
    username: train_user
    password: train_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true
    clean-disabled: true

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/train_db_dev?retryWrites=true&w=majority

logging:
  level:
    root: INFO
    com.train: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

server:
  port: 8080
