spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${KEYCLOAK_DOMAIN}/realms/train
          jwk-set-uri: https://${KEYCLOAK_DOMAIN}/realms/train/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/train_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/train?retryWrites=true&w=majority

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: WARN
    com.train: INFO